---

- import_tasks: install.yml
  tags: [repmgr, repmgr-install]

- import_tasks: configure.yml
  tags: [repmgr, repmgr-configure]

- import_tasks: bootstrap.yml
  when: repmgr_bootstrap|bool
  tags: [repmgr, repmgr-bootstrap]

- import_tasks: cron_jobs.yml
  when: repmgr_cron_status
  tags: [repmgr, repmgr-cron]
