---

- name: start repmgrd
  systemd:
    name: repmgrd
    state: started
  become: true

- name: stop repmgrd
  systemd:
    name: repmgrd
    state: stop
  become: true

- name: restart repmgrd
  systemd:
    name: repmgrd
    state: restarted
  become: true

- name: reload repmgrd
  systemd:
    name: repmgrd
    state: reloaded
  become: true
